[book]
authors = ["Jeremy H. Carroll"]
language = "en"
src = "book"
title = "Simplex Normal Forms Book"

[output.html]
git-repository-url = "https://github.com/dbccpage/simplex-normal-forms"

[output.pdf]
output-filename = "simplex-normal-forms.pdf"
